#!/bin/bash

if [ $1 == "configure" ]; then

        test -e /etc/xbian-initramfs/update-initramfs.sh && /etc/xbian-initramfs/update-initramfs.sh "3.8.12-2+" > /dev/null 2>&1
        rm -f /boot/kernel.img.prev || true
        mountpoint -q /boot && umount /boot

fi
