#!/bin/bash

KVER="3.8.13+"
fpool="/boot/kernel3_8_13.img /boot/System3_8_13.map /boot/System.map-$KVER /boot/kernel.img-$KVER"

if [ $1 == "configure" ]; then

        mv /boot/kernel.img-$KVER /boot/kernel.img
        cp /boot/System.map-$KVER /boot/System.map
        depmod -a $KVER
        xbian-update-initramfs "$KVER"

        for f in $fpool; do
                { [ -f $f.xbian ] && rm $f.xbian; } || true
        done

        [ -d /lib/modules/3.8.13+.xbian ] && rm -fr /lib/modules/3.8.13+.xbian || true
fi
