#!/bin/bash

if [ $1 == "configure" ]; then

	cp /boot/kernel3_6_11.img /boot/kernel.img
	depmod -a
    xbian-update-initramfs "3.6.11+"

	if [ -f "/boot/kernel3_6_11.img.xbian" ]; then
		rm /boot/kernel3_6_11.img.xbian
	fi

fi
