#!/bin/bash

KVER="3.10.1+"
fpool="/boot/System.map-$KVER /boot/kernel.img-$KVER"

if [ $1 == "configure" ]; then

        mv /boot/kernel.img-$KVER /boot/kernel.img
        cp /boot/System.map-$KVER /boot/System.map
        depmod -a $KVER
        xbian-update-initramfs "$KVER"

        for f in $fpool; do
                { [ -f $f.xbian ] && rm $f.xbian; } || true
        done

        [ -d /lib/modules/$KVER.xbian ] && rm -fr /lib/modules/$KVER.xbian || true

        insserv -fr rng-tools &>/dev/null
fi
