#!/bin/sh

set +e

rndname=$(basename $DEVNAME)
[ $DEVNAME = /dev/urandom ] && OPPOSITE=/dev/frandom
[ $DEVNAME = /dev/random ] && OPPOSITE=/dev/erandom
[ $DEVNAME = /dev/frandom ] && OPPOSITE=/dev/urandom
[ $DEVNAME = /dev/erandom ] && OPPOSITE=/dev/random

case $rndname in
    urandom|random)
        test -e $OPPOSITE && { mv $DEVNAME $DEVNAME.orig; ln $OPPOSITE $DEVNAME; }
        ;;
    frandom|erandom)
        test -e $OPPOSITE && { mv $OPPOSITE $OPPOSITE.orig; ln $DEVNAME $OPPOSITE; }
        ;;
esac
